name: Add Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1.0.2
        with:
          project-url: https://github.com/users/joe-mccarthy/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
